apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpguitars-deployment
spec:
  selector:
    matchLabels:
      run: jpguitars-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: jpguitars-deployment
    spec:
      containers:
      - name: jpguitars
        image: jlessey/jpguitars:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
            